# based on: https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: Continuous Integration
on: [pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-targets --all-features --examples
      - name: Test with no features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-targets --no-default-features --examples
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add rustfmt component
        run: rustup component add rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add clippy component
        run: rustup component add clippy
      - name: Check style
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets --all-features -- -D warnings
